services:
  app:
    # nextjs application
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=local
