export const plans = [
  {
    name: 'Essencial',
    price: 'R$ 279,00',
    period: '/mês',
    description: 'Perfeito para marmorarias pequenas',
    mpPlanId: process.env.NEXT_PUBLIC_MP_PLAN_ID_ESSENCIAL,
    planKey: 'essencial',
    features: [
      'Até 2 usuários',
      'Gestão de estoque básica',
      'Orçamentos ilimitados',
      'Relatórios básicos',
      'Suporte por email',
    ],
    popular: false,
  },
  {
    name: 'Profissional',
    price: 'R$ 397,00',
    period: '/mês',
    description: 'Ideal para empresas em crescimento',
    mpPlanId: process.env.NEXT_PUBLIC_MP_PLAN_ID_PROFISSIONAL,
    planKey: 'profissional',
    features: [
      'Até 10 usuários',
      'Gestão completa de estoque',
      'Orçamentos e contratos',
      'Relatórios avançados',
      'Suporte prioritário',
      'Integração com WhatsApp',
    ],
    popular: true,
  },
];
