name: Frontend - Deploy Production

on:
  push:
    branches:
      - main

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar TAG automática
        id: tag
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          git tag $VERSION
          git push origin $VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js
        run: yarn build

      - name: Deploy Produção na Vercel
        run: npx vercel deploy --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
