name: Frontend - Deploy Develop 

on:
  push:
    branches:
      - develop

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js
        run: yarn build

      - name: Deploy Preview na Vercel
        run: npx vercel deploy --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
